// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropGenreIdColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropGenreIdColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281444183_DropGenreIdColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
